# Generated by Django 3.2.9 on 2021-11-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('favorite', models.BooleanField()),
                ('difficulty', models.CharField(choices=[('Facile', 'Facile'), ('Intermédiaire', 'Intermédiaire'), ('Difficile', 'Difficile')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.JSONField()),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recette.recette')),
            ],
        ),
    ]
