# Generated by Django 3.2.9 on 2021-11-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('recette', '0003_auto_20211116_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='category.categorierecette'),
        ),
    ]
