# Generated by Django 3.2.9 on 2021-11-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '__first__'),
        ('recette', '0004_alter_recette_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='recette',
            name='time',
        ),
        migrations.AddField(
            model_name='recette',
            name='time_cooking',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='time_preparation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='image.imagesrecette'),
        ),
    ]
