# Generated by Django 3.2.9 on 2021-11-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0005_auto_20211130_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='img',
        ),
    ]
