# Generated by Django 3.2.9 on 2021-11-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '__first__'),
        ('recette', '0006_remove_recette_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='image.imagesrecette'),
        ),
    ]
